import Image from 'next/image'
export const metadata = {
  title: 'Home page',
  description: 'Generated by create next app',
}


export default function Home() {
  return (
   <div>
    <h1 className='text-center text-red-500'>Welcome to next js </h1>
   </div>
  )
}
